export enum TypePlanning {
  WEEKEND = 'WEEKEND',
  VACANCES = 'VACANCES',
  CONGES = 'CONGES',
  MALADIE = 'MALADIE',
  FORMATION = 'FORMATION',
  TELETRAVAIL = 'TELETRAVAIL',
  DEPLACEMENT = 'DEPLACEMENT',
  REUNION = 'REUNION',
  PROJET = 'PROJET',
  AUTRE = 'AUTRE'
}
